[2020-06-29 12:59:28,717] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.generate_csv 2020-06-29T00:00:00+00:00 [queued]>
[2020-06-29 12:59:28,727] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.generate_csv 2020-06-29T00:00:00+00:00 [queued]>
[2020-06-29 12:59:28,727] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:59:28,727] {taskinstance.py:880} INFO - Starting attempt 5 of 6
[2020-06-29 12:59:28,727] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:59:28,736] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): generate_csv> on 2020-06-29T00:00:00+00:00
[2020-06-29 12:59:28,738] {standard_task_runner.py:53} INFO - Started process 6937 to run task
[2020-06-29 12:59:28,776] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.generate_csv 2020-06-29T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 12:59:28,789] {taskinstance.py:1145} ERROR - type object argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/generate_csv.py", line 14, in generate_csv
    spark_df = spark.createDataFrame(Row(**x) for x in dict_data)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 748, in createDataFrame
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 413, in _createFromLocal
    data = list(data)
  File "/home/nineleaps/airflow/plugins/generate_csv.py", line 14, in <genexpr>
    spark_df = spark.createDataFrame(Row(**x) for x in dict_data)
TypeError: type object argument after ** must be a mapping, not str
[2020-06-29 12:59:28,790] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-29 12:59:38,716] {logging_mixin.py:112} INFO - [2020-06-29 12:59:38,714] {local_task_job.py:103} INFO - Task exited with return code 1
