[2020-06-28 19:39:30,292] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 19:39:30,299] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 19:39:30,300] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 19:39:30,300] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-28 19:39:30,300] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 19:39:30,307] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-28 19:39:30,309] {standard_task_runner.py:53} INFO - Started process 8924 to run task
[2020-06-28 19:39:30,347] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-28 19:39:30,472] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-28 19:39:30,475] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200628T140930, end_date=20200628T140930
[2020-06-28 19:39:40,292] {logging_mixin.py:112} INFO - [2020-06-28 19:39:40,291] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-28 19:49:18,532] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 19:49:18,539] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 19:49:18,539] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 19:49:18,539] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-28 19:49:18,539] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 19:49:18,546] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-28 19:49:18,548] {standard_task_runner.py:53} INFO - Started process 13505 to run task
[2020-06-28 19:49:18,599] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-28 19:49:18,757] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-28 19:49:18,760] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200628T141918, end_date=20200628T141918
[2020-06-28 19:49:28,533] {logging_mixin.py:112} INFO - [2020-06-28 19:49:28,532] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-28 20:00:53,644] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 20:00:53,651] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 20:00:53,651] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 20:00:53,651] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-28 20:00:53,651] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 20:00:53,658] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-28 20:00:53,660] {standard_task_runner.py:53} INFO - Started process 3759 to run task
[2020-06-28 20:00:53,695] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-28 20:00:54,257] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-28 20:00:54,261] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200628T143053, end_date=20200628T143054
[2020-06-28 20:01:03,653] {logging_mixin.py:112} INFO - [2020-06-28 20:01:03,652] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-28 20:09:03,365] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 20:09:03,374] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 20:09:03,375] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 20:09:03,375] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-28 20:09:03,375] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 20:09:03,382] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-28 20:09:03,384] {standard_task_runner.py:53} INFO - Started process 7874 to run task
[2020-06-28 20:09:03,437] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-28 20:09:03,930] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-28 20:09:03,933] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200628T143903, end_date=20200628T143903
[2020-06-28 20:09:13,368] {logging_mixin.py:112} INFO - [2020-06-28 20:09:13,367] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-28 20:23:44,478] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 20:23:44,485] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-28 20:23:44,486] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 20:23:44,486] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-28 20:23:44,486] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 20:23:44,493] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-28 20:23:44,495] {standard_task_runner.py:53} INFO - Started process 13805 to run task
[2020-06-28 20:23:44,545] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-28 20:23:44,727] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-28 20:23:44,730] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200628T145344, end_date=20200628T145344
[2020-06-28 20:23:54,475] {logging_mixin.py:112} INFO - [2020-06-28 20:23:54,475] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-29 11:21:16,830] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 11:21:16,838] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 11:21:16,838] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:21:16,838] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-29 11:21:16,838] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:21:16,845] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-29 11:21:16,846] {standard_task_runner.py:53} INFO - Started process 3737 to run task
[2020-06-29 11:21:16,886] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 11:21:17,192] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-29 11:21:17,195] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200629T055116, end_date=20200629T055117
[2020-06-29 11:21:26,831] {logging_mixin.py:112} INFO - [2020-06-29 11:21:26,830] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-29 11:57:27,153] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 11:57:27,160] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 11:57:27,160] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:57:27,160] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-29 11:57:27,161] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:57:27,168] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-29 11:57:27,170] {standard_task_runner.py:53} INFO - Started process 3538 to run task
[2020-06-29 11:57:27,205] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 11:57:27,520] {taskinstance.py:1145} ERROR - global name 'valid_data' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/extract.py", line 27, in extract
    pandas_df = pd.DataFrame(valid_data)
NameError: global name 'valid_data' is not defined
[2020-06-29 11:57:27,523] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-29 11:57:37,152] {logging_mixin.py:112} INFO - [2020-06-29 11:57:37,151] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-29 12:00:47,773] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 12:00:47,780] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 12:00:47,780] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:00:47,780] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-29 12:00:47,780] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:00:47,789] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-29 12:00:47,790] {standard_task_runner.py:53} INFO - Started process 4865 to run task
[2020-06-29 12:00:47,826] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 12:00:48,108] {taskinstance.py:1145} ERROR - 'date'
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/extract.py", line 28, in extract
    pandas_df['date'] = pd.to_datetime(pandas_df['date'], format="%d-%b-%y").dt.date
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'
[2020-06-29 12:00:48,115] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-29 12:00:57,761] {logging_mixin.py:112} INFO - [2020-06-29 12:00:57,760] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-29 12:12:21,013] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 12:12:21,021] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 12:12:21,021] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:12:21,021] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-29 12:12:21,021] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:12:21,029] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): extract> on 2020-06-27T00:00:00+00:00
[2020-06-29 12:12:21,031] {standard_task_runner.py:53} INFO - Started process 8359 to run task
[2020-06-29 12:12:21,071] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.extract 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 12:12:21,310] {logging_mixin.py:112} INFO - Empty DataFrame
Columns: [date, status, state, count]
Index: []
[2020-06-29 12:12:21,327] {logging_mixin.py:112} INFO - data cleaned successfully !!
[2020-06-29 12:12:21,328] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-29 12:12:21,331] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=covid_stats, task_id=extract, execution_date=20200627T000000, start_date=20200629T064221, end_date=20200629T064221
[2020-06-29 12:12:31,010] {logging_mixin.py:112} INFO - [2020-06-29 12:12:31,010] {local_task_job.py:103} INFO - Task exited with return code 0
