[2020-06-28 19:34:44,859] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats_2.validate_and_clean_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-28 19:34:44,870] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats_2.validate_and_clean_data 2020-05-31T00:00:00+00:00 [queued]>
[2020-06-28 19:34:44,870] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 19:34:44,870] {taskinstance.py:880} INFO - Starting attempt 1 of 6
[2020-06-28 19:34:44,870] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-28 19:34:44,878] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): validate_and_clean_data> on 2020-05-31T00:00:00+00:00
[2020-06-28 19:34:44,880] {standard_task_runner.py:53} INFO - Started process 6385 to run task
[2020-06-28 19:34:44,916] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats_2.validate_and_clean_data 2020-05-31T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-28 19:34:44,928] {taskinstance.py:1145} ERROR - expected string or buffer
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/validate_and_clean_data.py", line 25, in validate_and_clean_data
    dict_data = json.loads(kwargs['ti'].xcom_pull(dag_id='covid_stats', key='api_response'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[2020-06-28 19:34:44,931] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-28 19:34:54,860] {logging_mixin.py:112} INFO - [2020-06-28 19:34:54,859] {local_task_job.py:103} INFO - Task exited with return code 1
