[2020-06-29 11:29:11,848] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.generate_csv 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 11:29:11,862] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.generate_csv 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 11:29:11,862] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:29:11,862] {taskinstance.py:880} INFO - Starting attempt 2 of 6
[2020-06-29 11:29:11,862] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 11:29:11,869] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): generate_csv> on 2020-06-27T00:00:00+00:00
[2020-06-29 11:29:11,872] {standard_task_runner.py:53} INFO - Started process 7708 to run task
[2020-06-29 11:29:11,916] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.generate_csv 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 11:29:11,932] {taskinstance.py:1145} ERROR - type object argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/generate_csv.py", line 14, in generate_csv
    spark_df = spark.createDataFrame(Row(**x) for x in dict_data)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 748, in createDataFrame
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 413, in _createFromLocal
    data = list(data)
  File "/home/nineleaps/airflow/plugins/generate_csv.py", line 14, in <genexpr>
    spark_df = spark.createDataFrame(Row(**x) for x in dict_data)
TypeError: type object argument after ** must be a mapping, not str
[2020-06-29 11:29:11,932] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-29 11:29:21,847] {logging_mixin.py:112} INFO - [2020-06-29 11:29:21,846] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-29 12:14:57,576] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.generate_csv 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 12:14:57,587] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_stats.generate_csv 2020-06-27T00:00:00+00:00 [queued]>
[2020-06-29 12:14:57,587] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:14:57,587] {taskinstance.py:880} INFO - Starting attempt 2 of 6
[2020-06-29 12:14:57,588] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-29 12:14:57,595] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): generate_csv> on 2020-06-27T00:00:00+00:00
[2020-06-29 12:14:57,597] {standard_task_runner.py:53} INFO - Started process 9237 to run task
[2020-06-29 12:14:57,636] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_stats.generate_csv 2020-06-27T00:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-29 12:14:57,648] {taskinstance.py:1145} ERROR - can not infer schema from empty dataset
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/plugins/generate_csv.py", line 14, in generate_csv
    spark_df = spark.createDataFrame(Row(**x) for x in dict_data)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 748, in createDataFrame
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 416, in _createFromLocal
    struct = self._inferSchemaFromList(data, names=schema)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/pyspark/sql/session.py", line 343, in _inferSchemaFromList
    raise ValueError("can not infer schema from empty dataset")
ValueError: can not infer schema from empty dataset
[2020-06-29 12:14:57,649] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-29 12:15:07,570] {logging_mixin.py:112} INFO - [2020-06-29 12:15:07,569] {local_task_job.py:103} INFO - Task exited with return code 1
